<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
global $APPLICATION;
$APPLICATION->AddChainItem('Главная', '/');
$APPLICATION->SetPageProperty("keywords", "элитный дизайн квартир портфолио, фото элитных интерьеров, примеры элитного дизайна квартир, дизайн элитных квартир в современном стиле, лофт дизайн элитных квартир спб, интерьер элитных квартир фото, дизайн четырехкомнатной квартиры элитный, дизайн проект квартиры студии премиум, лучшие интерьеры квартир спб");
$APPLICATION->SetPageProperty("title", "Дизайн офисов: портфолио и реализованные проекты в СПб | Студия Maxdesign");
$APPLICATION->SetPageProperty("description", "Посмотрите примеры дизайна интерьера офисов от студии Maxdesign в Санкт-Петербурге. В нашем портфолио — современные офисные пространства, планировки и реальные фото реализованных объектов.");
$APPLICATION->SetTitle("Портфолио: Элитный дизайн квартир");
?>

<?php

$APPLICATION->IncludeComponent(
    "bitrix:news",
    "projects",
    array(
        "ADD_ELEMENT_CHAIN" => "Y",
        "ADD_SECTIONS_CHAIN" => "Y",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "BROWSER_TITLE" => "-",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "Y",
        "CACHE_TIME" => "36000000",
        "CACHE_TYPE" => "N",
        "CHECK_DATES" => "Y",
        "COMPONENT_TEMPLATE" => "projects",
        "DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
        "DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
        "DETAIL_DISPLAY_TOP_PAGER" => "N",
        "DETAIL_FIELD_CODE" => array(
            0 => "PREVIEW_TEXT",
            1 => "DETAIL_TEXT",
            2 => "",
        ),
        "DETAIL_PAGER_SHOW_ALL" => "Y",
        "DETAIL_PAGER_TEMPLATE" => "",
        "DETAIL_PAGER_TITLE" => "Страница",
        "DETAIL_PROPERTY_CODE" => array(
            0 => "AUTHOR",
            1 => "YEAR",
            2 => "DETAIL",
            3 => "ADDRESS",
            4 => "SQUARE",
            5 => "STATUS",
            6 => "STYLE",
            7 => "TYPE",
            8 => "SLIDER",
            9 => "",
        ),
        "DETAIL_SET_CANONICAL_URL" => "N",
        "DISPLAY_BOTTOM_PAGER" => "Y",
        "DISPLAY_DATE" => "Y",
        "DISPLAY_NAME" => "Y",
        "DISPLAY_PICTURE" => "Y",
        "DISPLAY_PREVIEW_TEXT" => "Y",
        "DISPLAY_TOP_PAGER" => "N",
        "FILE_404" => "",
        "HIDE_LINK_WHEN_NO_DETAIL" => "N",
        "IBLOCK_ID" => "6",
        "IBLOCK_TYPE" => "portfolio",
        "INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
        "LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
        "LIST_FIELD_CODE" => array(
            0 => "PREVIEW_PICTURE",
            1 => "",
        ),
        "LIST_PROPERTY_CODE" => array(
            0 => "YEAR",
            1 => "INCLUDING",
            2 => "SQUARE",
            3 => "STATUS",
            4 => "TYPE",
            5 => "CATEGORY",
            6 => "RATIO",
            7 => "",
        ),
        "MESSAGE_404" => "",
        "META_DESCRIPTION" => "-",
        "META_KEYWORDS" => "-",
        "NEWS_COUNT" => 20, //9999
        "PAGER_BASE_LINK_ENABLE" => "N",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_TEMPLATE" => "projects",
        "PAGER_TITLE" => "Портфолио",
        "PREVIEW_TRUNCATE_LEN" => "",
        "SEF_FOLDER" => "/portfolio/",
        "SEF_MODE" => "Y",
        "SET_LAST_MODIFIED" => "N",
        "SET_STATUS_404" => "Y",
        "SET_TITLE" => "Y",
        "SHOW_404" => "N",
//		"SORT_BY1" => "ACTIVE_FROM",
//		"SORT_BY2" => "SORT",
        "SORT_BY1" => "ID",
        "SORT_BY2" => "SORT",
        "SORT_ORDER1" => "DESC",
        "SORT_ORDER2" => "ASC",
        "STRICT_SECTION_CHECK" => "N",
        "USE_CATEGORIES" => "N",
        "USE_FILTER" => "Y",
        "USE_PERMISSIONS" => "N",
        "USE_RATING" => "N",
        "USE_RSS" => "N",
        "USE_SEARCH" => "N",
        "USE_SHARE" => "N",
        "SEF_URL_TEMPLATES" => array(
            "news" => "",
            "section" => "#SECTION_CODE_PATH#/",
            "detail" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#",
        ),
        'IBLOCK_TYPE_SLIDER' => 'portfolio',
        'IBLOCK_ID_SLIDER' => 19,
        'NEWS_COUNT_SLIDER' => 20,
        'SORT_BY1_SLIDER' => 'ID',
        'SORT_ORDER1_SLIDER' => 'DESC',
        'SORT_BY2_SLIDER' => 'SORT',
        'SORT_ORDER2_SLIDER' => 'ASC',
        'FILTER_NAME_SLIDER' => 'arrFilterSlider',
        'IBLOCK_TYPE_FILTERS' => 'portfolio',
        'IBLOCK_ID_FILTERS' => 20,
        'NEWS_COUNT_FILTERS' => 5,
        'SORT_BY1_FILTERS' => 'SORT',
        'SORT_ORDER1_FILTERS' => 'ASC',
        'SORT_BY2_FILTERS' => 'ID',
        'SORT_ORDER2_FILTERS' => 'DESC',
        'FILTER_NAME_FILTERS' => 'arrFilterFilters',
    ),
    false
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>